### ISSUE TITLE
El nombre del estado standby no es descriptivo.

### ISSUE THREAD

**Issue by cosmopaco** [peninquen/Modbus-Energy-Monitor-Arduino#12]
Creo que se debería renombrar como WAITING_FOR_TURNAROUND .
O como el objeto que realmente se ejecuta POLL_INTERVAL,

**Comment by peninquen** [comment]
¿Algo como 'WAITING_NEXT_POLL'?

**Comment by cosmopaco** [comment]
Adjudicado.!!!

Esto plantea volver ha definir lo mejor posible la máquina de estado.
#define IDLE
#define SEND
#define SENDING  
#define RECEIVING 
#define WAITING_NEXT_POLL  

Lo he escrito a lo loco,

**Comment by peninquen** [comment]
No lo había leido y escrito algo similar en el otro hilo!!!

**Comment by peninquen** [comment]
¿Lo dejamos así?

SEND (controla indexSensor y sendFrame())
SENDING  (espera a vaciar el buffer de escritura)
RECEIVING (espera a recibir la respuesta y la procesa o TimeOut)
IDLE (espera a que se recupere el Bus T3.5, o el SDM)
WAITING_NEXT_POLL (periodo entre muestreos de lotes)
