### ISSUE TITLE
Optimizar estado RECEIVING

### ISSUE THREAD

**Issue by cosmopaco** [peninquen/Modbus-Energy-Monitor-Arduino#14]
Es posible optimizar el tiempo de estado receiving utilizando Serial.peek ya que esperamos una trama de un tamaño mínimo. de  x bytes,
https://www.arduino.cc/en/Serial/Peek

**Comment by peninquen** [comment]
Si la trama de respuesta es de tamaño conocido se puede esperar a recibirla entera, el problema es que las respuestas erróneas tienen otro tamaño.
la función a utilizar no es peek, es available()
[https://www.arduino.cc/en/Serial/Available](https://www.arduino.cc/en/Serial/Available)

**Comment by cosmopaco** [comment]
Me he liado ,)
