### ISSUE TITLE
Funciones inline

### ISSUE THREAD

**Issue by peninquen** [peninquen/Modbus-Energy-Monitor-Arduino#15]
Decidir qué funciones se hacen inline o no para mejorar velocidad o para ahorrar memoria.

**Comment by cosmopaco** [comment]
Relacionado con Crear SDMUtility.h #3

**Comment by peninquen** [comment]
¿El compilador analiza el contenido de la función y el sketch para decidir cuáles hace inline implicitamente?

**Comment by peninquen** [comment]
He cambiado al archivo .h las funciones 'inline', en particular los 'template'
