### ISSUE TITLE
Eliminar la entrada de puerto serial del constructor modbusSensor.

### ISSUE THREAD

**Issue by cosmopaco** [peninquen/Modbus-Energy-Monitor-Arduino#16]
Ya hay una entrada en modbusSerial es confuso!!

Si la intención  es que puedan usarse mas de un bus sobrecargar la función.

**Comment by peninquen** [comment]
¿utilizar directivas del precompilador para saber en el constructor del modbusSensor dónde esta el modbusMaster al que colgarse? 
¿y si no ha creado el objeto MBSerial?

**Comment by peninquen** [comment]
En la librería .cpp he cambiado mbSerial por hwSerial para evitar confusiones con el objeto MBSerial de la clase modbusMaster.
voy a probar a definir en librería el objeto **_MBSerial**_, sobrecargar las funciones de sensores para que por defecto se conecten y desconecten del array

**Comment by peninquen** [comment]
Dejo un solo objeto MBSerial, no parece lógico gestionar más de un canal modbus, y elimino las referencias a la instancia de modbusMaster
