### ISSUE TITLE
Crear SDMUtility.h

### ISSUE THREAD

**Issue by cosmopaco** [peninquen/Modbus-Energy-Monitor-Arduino#3]
Crear un fichero cabecera, con macros o funciones de apoyo.
Las variables a leer o escribir en SDM estan diferentes formatos HEX, BCD y Float. Añadir las funciones o macros swapFloat, intToFloat, intToHex.

**Comment by peninquen** [comment]
Sigo sin ver qué funciones quieres poner en SDMUtility.h ahora mismo solo veo las tablas de direcciones del SDM120 y SDM630. 

En caso de que surjan otros dispositivos modbus lo segregamos, mientra tanto lo veo dispersión.

**Comment by cosmopaco** [comment]
Es cierto, como se estructurado actualmente no tiene utilidad.
Si se añade las tramas de configuración tendria mas sentido.
