### ISSUE TITLE
Como realizar la conexion y lectura de mas de un medidor??

### ISSUE THREAD

**Issue by LeoHenrik** [peninquen/Modbus-Energy-Monitor-Arduino#43]
He realizado la conexion de un medidor utilizando la libreria normal de sdm.h pero no logro entender como al conectar otro medidores en paralelo A y B, como deberia especificar el numero del esclavo y como extraer los parametros que requiero.

**Comment by LeoHenrik** [comment]
> He realizado la conexion de un medidor utilizando la libreria normal de sdm.h pero no logro entender como al conectar otro medidores en paralelo A y B, como deberia especificar el numero del esclavo y como extraer los parametros que requiero.

**Comment by ogromis** [comment]
Hello,

Sorry but I dont understand anything. Can you write in English?

Regards

śr., 29 sty 2020 o 16:26 LeoHenrik <notifications@github.com> napisał(a):

**Comment by LeoHenrik** [comment]
I have other question, do you know how modify the ID address using arduino? or is necesary use other program for modify that?
